version: '2'

services:
  mariadb:
    image: mariadb:10.0.15
    environment:
      - MYSQL_ROOT_PASSWORD=password
  
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - 8888:80
      environment:
          - PMA_HOST=mariadb
